bias: true
bidirectional: false
bidirectional_fusion: concat
dropout: 0.4
future_hidden_size: 256
future_input_size: 0
future_layers: 1
group_identifier: gauge_id
hidden_size: 256
input_len: 270
input_size: 8
learning_rate: 0.0001
loss_fn: mse
loss_fn_kwargs: {}
num_layers: 1
output_len: 1
scheduler_factor: 0.5
scheduler_patience: 10
static_size: 22
training_mode: evaluation
use_rev_in: true
