d_conv: 4
d_model: 110
d_state: 16
decoder_hidden_size: 80
dropout: 0.4
expand: 2
future_input_size: 0
group_identifier: gauge_id
input_len: 270
input_size: 8
learning_rate: 0.0001
loss_fn: mse
loss_fn_kwargs: {}
n_layers: 3
output_len: 1
scheduler_factor: 0.5
scheduler_patience: 10
static_size: 22
training_mode: evaluation
use_rev_in: false
