data:
  base_path: ../CARAVAN_TRANSFORMED_NO_LOG_eval
  gauge_ids_file: configs/basin_ids_files/train_fold_5.txt
  pipeline_path: ../CARAVAN_TRANSFORMED_NO_LOG_eval/ts_pipeline.joblib
features:
  forcing:
    - temperature_2m_max
    - temperature_2m_min
    - potential_evaporation_sum_FAO_PENMAN_MONTEITH
    - potential_evaporation_sum_ERA5_LAND
    - temperature_2m_mean
    - total_precipitation_sum
    - sin_day_of_year
    - cos_day_of_year
  static:
    - p_mean
    - area
    - ele_mt_sav
    - high_prec_dur
    - frac_snow
    - high_prec_freq
    - slp_dg_sav
    - cly_pc_sav
    - aridity_ERA5_LAND
    - aridity_FAO_PM
    - low_prec_dur
    - gauge_lat
    - snd_pc_sav
    - pet_mean_ERA5_LAND
    - gauge_lon
    - slt_pc_sav
    - low_prec_freq
    - glc_cl_smj
    - seasonality_ERA5_LAND
    - cmi_ix_syr
    - rdd_mk_sav
    - for_pc_sse
  target: streamflow
sequence:
  input_length: 270
  output_length: 1
data_preparation:
  mode: simulation
  is_autoregressive: false
  include_dates: true
model:
  type: ealstm
  overrides:
    # Architecture (275,716 parameters - matching paper configuration)
    hidden_size: 256
    num_layers: 1
    bidirectional: false
    bias: true

    # Regularization - matching paper
    dropout: 0.4

    # Training
    learning_rate: 0.0001
    scheduler_patience: 10
    scheduler_factor: 0.5
dataloader:
  batch_size: 1024
  num_workers: 8
  pin_memory: true
  persistent_workers: false
  shuffle_train: true
