bias: true
bidirectional: false
bidirectional_fusion: concat
dropout: 0.2
future_hidden_size: 150
future_input_size: 0
future_layers: 1
group_identifier: gauge_id
hidden_size: 150
input_len: 270
input_size: 11
learning_rate: 0.0001
loss_fn: power
loss_fn_kwargs:
  alpha: 2.5
num_layers: 1
output_len: 1
scheduler: cosine_annealing
scheduler_factor: 0.5
scheduler_kwargs:
  T_max: 50
  eta_min: 1.0e-05
scheduler_patience: 5
static_size: 22
training_mode: evaluation
use_rev_in: false
